// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Web_Api_CRUD.Infraestructure;

#nullable disable

namespace Web_Api_CRUD.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Web_Api_CRUD.Model.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("Web_Api_CRUD.Model.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("Lista")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("pedidos");
                });

            modelBuilder.Entity("Web_Api_CRUD.Model.PedidoProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorTotalLinha")
                        .HasColumnType("numeric");

                    b.Property<Guid>("idPedido")
                        .HasColumnType("uuid");

                    b.Property<Guid>("idProduto")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("idPedido")
                        .IsUnique();

                    b.HasIndex("idProduto")
                        .IsUnique();

                    b.ToTable("pedidoProdutos");
                });

            modelBuilder.Entity("Web_Api_CRUD.Model.Produto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.ToTable("produtos");
                });

            modelBuilder.Entity("Web_Api_CRUD.Model.PedidoProduto", b =>
                {
                    b.HasOne("Web_Api_CRUD.Model.Pedido", "pedido")
                        .WithOne("pedidoProduto")
                        .HasForeignKey("Web_Api_CRUD.Model.PedidoProduto", "idPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_Api_CRUD.Model.Produto", "produto")
                        .WithOne("pedidoProduto")
                        .HasForeignKey("Web_Api_CRUD.Model.PedidoProduto", "idProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pedido");

                    b.Navigation("produto");
                });

            modelBuilder.Entity("Web_Api_CRUD.Model.Pedido", b =>
                {
                    b.Navigation("pedidoProduto")
                        .IsRequired();
                });

            modelBuilder.Entity("Web_Api_CRUD.Model.Produto", b =>
                {
                    b.Navigation("pedidoProduto")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
